services:
  koala:
    build: .
    image: koala-monitoring:latest
    container_name: koala
    ports:
      - "3000:3000"
    volumes:
      - koala-data:/app/data
    environment:
      - KOALA_TIMEZONE=Asia/Kolkata
      - ALERT_THRESHOLD=3
      - ALERT_COUNTDOWN=900000
      - PORT=3000
      - NODE_ENV=production
      - DOCKER=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_mail
      - SMTP_PASS=_your_app_pass
      - SMTP_FROM=Koala Monitor
    restart: unless-stopped

volumes:
  koala-data:
